spring:
  application:
     name: student-service
     
server:
   port: 9095

management:
   endpoints:
      web:
         exposure:
            include: "*"
            
logging:
   file: /logs/student-json.log  